[WIP] operator sdk mig
fedora-infra/mbbox pull request #130
Opened 2020-11-10 14:43 UTC by odra

Docs and CI jobs need to be updated but the code itself can be tested an reviewed.

## Proposed Changes

* SDK version migration to 1.x

## Verification Steps

* From `mbox-operator` run `molecule test -s test-local`;
* Start minikube or openshift 4 (CRC) and run `molecule test`;

## Additional Notes

Lots of changes due to SDK architectural changes.

The roles themselves had minimum to no changes, biggest changes were around tests and config files structure/organization. 

Running tests now require the `kind` CLI tool: https://github.com/kubernetes-sigs/kind

2020-11-16 13:32 UTC, morucci commented
recheck

2020-11-23 14:10 UTC, Zlopez commented
Let's merge it if the tests are passing. I will try to update the Vagrant to F33 with this already in.

2020-11-23 14:23 UTC, Zlopez requested changes
Two changes remain.

2020-11-23 14:23 UTC, Zlopez commented on ci/roles/openshift-osdk/defaults/main.yml
> +minikube_version: 'latest'
Not sure if this is a good idea:
+ On one side we will be notified of any error soon as it occures
- We can have errors where we don't expect them

I would be rather to use specific version, the latest is now `1.15.2`

2020-11-23 14:23 UTC, Zlopez commented on ci/test-cluster.yml
> +        OPERATOR_IMAGE: "quay.io/lrossett/mbox-operator:dev"
Let's use the fedora namespace for this.

2020-11-23 15:22 UTC, odra commented
recheck

2020-11-23 15:44 UTC, odra commented
recheck

2020-11-23 17:10 UTC, Zlopez approved these changes

2020-11-23 18:24 UTC, odra commented
recheck

2020-11-24 08:41 UTC, Zlopez commented
The [kind issue](https://github.com/bsycorp/kind/issues/39) is now fixed, you can try it with `latest-1.19`.

2020-11-24 11:25 UTC, odra commented
latest-1.19 gave an error in my laptop as well, did it work for you?

2020-11-24 12:01 UTC, Zlopez commented
The API wasn't available in vagrant. So I will try 1.18

2020-11-24 12:09 UTC, odra commented
I think that route (/kubernetes-ready) doesn't work anymore, let me try a change in the tests.

2020-11-24 12:17 UTC, Zlopez commented
In 1.18 I'm getting "Failed to establish a new connection" when creating a namespace.

2020-11-24 12:22 UTC, odra commented
yeah I think I got it.. gimme 30 mins or so

2020-11-24 12:31 UTC, odra commented
fingers crossed!

2020-11-24 12:39 UTC, Zlopez commented
You got the same error I'm getting in vagrant.

2020-11-24 12:42 UTC, odra commented
it is ignoring the KUBECONFIG env var for some reason

2020-11-24 13:41 UTC, Zlopez commented
I noticed `server: https://localhost:10443` instead of `https://localhost:8443` you are checking in next step.

2020-11-24 13:50 UTC, Zlopez commented
I noticed the `k8s` is trying to check the version on `http://localhost:80/version`. Checking the docker container, I don't see anything running on port 80

2020-11-24 14:06 UTC, odra commented
it should be using the config file form KUBECONFIG env var ( /tmp/molecule/kind-test-local/kubeconfig) which has the correct url and port.

2020-11-24 14:36 UTC, Zlopez commented
It is possible, that the k8s is looking for the file in remote machine?

2020-11-24 14:38 UTC, odra commented
it runs on localhost, I ssh'ed into the machine and ran mocule as sudo and got the same error.

2020-11-24 14:40 UTC, odra commented
and.. the same error happens without sudo for some reason :)

2020-11-24 16:03 UTC, merged